### ISSUE TITLE
Garbled serial output from ATtiny1616 when using Platformio IDE, OK on Arduino IDE

### ISSUE THREAD

**Issue by ArnieO** [platformio/platform-atmelmegaavr#22]
Code in PlatformIO IDE:
```
#include <Arduino.h>
void setup() {
  Serial.swap(1);       // Switch to alternate serial port.
  Serial.begin(115200);
  while (!Serial);
}
void loop() {
  Serial.println("Hello world!");
  delay(1000);
}
```
platformio.ini:
```
[env:ATtiny1616]
platform = atmelmegaavr
board = ATtiny1616
framework = arduino
upload_port = COM24
monitor_port = COM10
monitor_speed = 115200
```

- When I build and upload this from PlatformIO IDE the serial output on alternate USART pins (PA1, PA2) is garbled (output looks like wrong baud rate):
![image](https://user-images.githubusercontent.com/10295178/107396993-8fb25a80-6afe-11eb-9ee8-8172328a5241.png)
- If I use primary USART (delete `Serial.swap(1) `or replace it with `Serial.swap(0)`) the same output continues on alternate USART, nothing on primary USART. I tried `Serial.pins()` instead of `Serial.swap()` -> same result.
- Same code built on Arduino IDE (except first #include line) works as expected, both on primary and alternate USART.

In both cases I program via UPDI / jtag2updi.

Any advise on what is going on here would be highly appreciated, as I prefer working in PlatformIO IDE.

**Comment by MCUdude** [comment]
Issue can probably be closed. It turned out to be an incorrect oscillator setting. The fuses.py script would have solved this
