### ISSUE TITLE
Board macros have different name than expected

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-atmelmegaavr#26]
See https://community.platformio.org/t/impossible-to-build-adafruit-gfx-with-platformio/21009/5?u=maxgerhardt. 

Situation: Attempt to compile a Adafruit GFX Sketch with the `platformio.ini`
```
[env:ATmega4809]
platform = atmelmegaavr
board = ATmega4809
framework = arduino
lib_ldf_mode = chain+
lib_deps =
     adafruit/Adafruit GFX Library @ ^1.10.7
     adafruit/Adafruit BusIO @ ^1.7.3
     SPI
     Wire
```

The Adafruit GFX Core tries to detect the ATMega4809 with [the code](https://github.com/adafruit/Adafruit_BusIO/blob/13bd6906a62b5f2e8cbe8529f55ad13880ffd730/Adafruit_SPIDevice.h#L6-L33)

```
..  defined(ARDUINO_AVR_ATmega4809) || ...
```
However this core defines

https://github.com/platformio/platform-atmelmegaavr/blob/dcbaeb126497f08acf2914ce5b8ebb28de742d58/boards/ATmega4809.json#L4-L4

Notice the different upper/lowercase spelling.

This causes a compile failure for Adafruit GFX sketches which rely on this check to activate the definition of certain types (`BitOrder`). 

It should be double-checked whether PlatformIO makes a spelling mistake here and if the behavior in the MegaCoreX is the same.

The sketch compiles with `board = nano_every` correctly, but that's also a different Arduino core.

**Comment by maxgerhardt** [comment]
Maybe @MCUdude can check that with regards to the compatibility of the Adafruit GFX library with MegaCoreX? Original PR #2 with those macro names come from there.

**Comment by MCUdude** [comment]
Hi @maxgerhardt!

You're absolutely right, it's supposed to be `ARDUINO_AVR_ATmega4809` rather than `AVR_ATMEGA4809`. I'll provide a PR that fixes this

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-atmelmegaavr/pull/27
