### ISSUE TITLE
megaTinyCore has no CLOCKSOURCE

### ISSUE THREAD

**Issue by 5e3** [platformio/platform-atmelmegaavr#28]
Spence Konde's cores use a compiler switch -DCLOCK_SOURCE. (See i.e.:  \.platformio\packages\framework-arduino-megaavr-megatinycore\cores\megatinycore\wiring.c:552) 
In platform-atmelmegaavr/builder/frameworks/arduino.py:77 there is a typo: it's called CLOCKSOURCE instead of CLOCK_SOURCE.

**Comment by valeros** [comment]
Resolved in #29
