### ISSUE TITLE
Update MegaCoreX to the latest version

### ISSUE THREAD

**Issue by MCUdude** [platformio/platform-atmelmegaavr#51]
Already been discussed in https://github.com/platformio/platform-atmelavr/issues/301, so this is just a reminder.

@valeros it would be great if you could update [MegaCoreX](https://github.com/MCUdude/MegaCoreX) to the latest version, v1.1.1? Avrdude can also be updated to v7.1. If all targets in this repo are using the same avrdude.conf file as the one shipped with the Avrdude binary, The entire repo could be configured to use Avrdude 7.1, which is a huge improvement over the current 6.3.

**Comment by valeros** [comment]
Updated to v1.1.1. I'm not sure about the latest AVRDUDE package and have no boards at hand to test it out with, so only MegaCoreX uses v7.1 right now.
