### ISSUE TITLE
Upgrade framework-arduino-megaavr-megatinycore to 2.6.5

### ISSUE THREAD

**Issue by mairas** [platformio/platform-atmelmegaavr#53]
Upstream megaTinyCore has significant improvements and bugfixes. Could you please upgrade `framework-arduino-megaavr-megatinycore`?

Thanks! 😊

**Comment by SpenceKonde** [comment]
@mairas 2.6.4? sometime in the early morning on monday 2.6.5 mTC along with 1.5.4 DxC was released 

Right now, to the best of my knowledge, both of the cores are in pretty good shape, and I don't forsee anything big in the next few months, so this would be a good time to do it,

**Comment by mairas** [comment]
Cool! Didn't visit the page before opening this issue, so my info was a couple of days too old. :-D Updated the request title.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-atmelmegaavr/commit/89c1b5cbcdba7cbf5895a3c506a6822146780120
